# Generated by Django 5.0.4 on 2024-04-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urok2_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='reg_date',
        ),
    ]
