# Generated by Django 5.0.4 on 2024-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok2_models', '0002_rename_order_date_order_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FilePathField(default=''),
        ),
    ]
